# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html

fos_rest:
    body_listener:
        enabled: true
    param_fetcher_listener:
        enabled: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            App\Exception\ResourceValidationException: 400
            App\Exception\ResourceNoAssociatedException: 404
            App\Exception\ResourceDoesNotExistException: 404
        messages:
            App\Exception\ResourceValidationException: true
            App\Exception\ResourceNoAssociatedException: true
            App\Exception\ResourceDoesNotExistException: true
