nelmio_api_doc:
    documentation:
        host: 127.0.0.1:8000
        schemes: [http]
        info:
            title: BileMo
            description: API BileMo
            version: 1.0.0
    areas:
       path_patterns:
           - ^/api(?!/doc$)
